/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721 } from "./ERC721";
export type { IERC165 } from "./IERC165";
export type { IERC721 } from "./IERC721";
export type { IERC721Receiver } from "./IERC721Receiver";
export type { Web3LearnNFT } from "./Web3LearnNFT";
