/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as demoWeb3LearnSol from "./DemoWeb3Learn.sol";
export * as sbtDemoSol from "./SBT_DEMO.sol";
export { Web3LearnDemoToken__factory } from "./Web3LearnDemoToken__factory";
