/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as demoWeb3LearnSol from "./DemoWeb3Learn.sol";
export type { demoWeb3LearnSol };
import type * as sbtDemoSol from "./SBT_DEMO.sol";
export type { sbtDemoSol };
export type { Web3LearnDemoToken } from "./Web3LearnDemoToken";
